# Generated by Django 5.1.1 on 2024-12-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
