# Generated by Django 5.1.4 on 2024-12-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_users_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='start_time',
        ),
    ]
