# Generated by Django 5.1.4 on 2024-12-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_courses_end_time_remove_courses_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='user',
        ),
        migrations.AddField(
            model_name='scan',
            name='scan',
            field=models.BooleanField(default=False),
        ),
    ]
